#:schema node_modules/wrangler/config-schema.json
name = "rin-server"
main = "server/src/_worker.ts"
compatibility_date = "2024-05-29"
# compatibility_flags = ["nodejs_compat"]
node_compat = true

[triggers]
crons = ["*/20 * * * *"]

[vars]
FRONTEND_URL = "https://xeu.life"
S3_FOLDER = "images/"
S3_CACHE_FOLDER="cache/"
S3_REGION = "auto"
S3_ENDPOINT = "<YourS3Emdpoint>"
S3_ACCESS_HOST = "<YourS3AccessHost>"
S3_BUCKET = "<YourS3BucketName>"
S3_FORCE_PATH_STYLE = "true"

[[d1_databases]]
binding = "DB"
database_name = "YourDatabaseName"
database_id = "YourDatabaseID"